---
# use this drops.json + any patches to start
base: ../OpenFusion/tdata/drops.json
patches:
  - ../OpenFusion/tdata/patch/1013/drops.json
# path of your xdt JSON file (xdt.json or xdt1013.json)
xdt: ../OpenFusion/tdata/xdt1013.json
# output folder will be created if not present, and the outputs will be inside this folder
output: target/
# yes generates a patch, no generates a single merged drops.json in the "output" folder
generate-patch: yes

# describe how you want to adjust the rarity of items here
items:
  # you can specify items with type name (or type id) and item id pairs...
  - type: Shirt
    id: 245

    # or if the item name uniquely describes the item, you can just use its name and omit type and id
    # though having all 3 specified is totally okay
    name: Open Circuit Shirt

    # then choose one of the below methods to describe the desired rarity of the item
    # we will try to match what is described here
    # if multiple ways are used to describe the rarity of the item, we will use one of them and disregard the rest
    # you will be shown what the achieved real rarity is at the end of the script

    # approximately how many kills from any mob get you the item, all crate and rarity rolls considered
    number-of-kills-till-item: 1200
    # approximately how many kills from certain mobs get you the item, all crate and rarity rolls considered
    number-of-kills-till-item-per-mob:
      # mob id and the number of kills
      123: 1200
      # or mob name (if it uniquely refers to 1 mob) and the number of kills
      Scoria Cephalopod: 1300
      # mobs not mentioned here will not have their rarities changed

    # approximately how many crates get you the item, all crate and rarity rolls considered
    number-of-crates-till-item: 250
    # approximately how many crates from certain crate types get you the item, all crate and rarity rolls considered
    # NOTE: only ONE of these will be matched, and that is the one that makes dropping this item easiest, so that we at least make the easiest case as hard as possible
    number-of-crates-till-item-per-crate-type:
      # negative values will be ignored
      ETC: -1
      # you can also just not mention certain crate types, they will be ignored as well
      # Standard: 10000
      # from the following, depending on the ability and chance to drop the rarity type of this item, the easiest drop chance will be approximately matched, and the others will be set to appropriate values
      Special: 1000
      Sooper: 500
      Sooper Dooper: 100
      # you can also use aliases for crate types, i.e. Gumball for ETC, Gray for Standard, Bronze or Orange for Special, Silver for Sooper, and Gold for Sooper Dooper
  - name: Couture Rifle
    number-of-kills-till-item: 12000
  # let's add a proper example for another item
  - name: Hot Pants Ray Gun
    number-of-crates-till-item-per-crate-type:
      Silver: 50
      Gold: 10
  # follow a similar example for your items, watch the spaces and make sure your text is aligned
  - type: 0
    id: 3
    number-of-kills-till-item: 30
