---
# use this drops.json + any patches to start
base: ../OpenFusion/tdata/drops.json
patches:
  - ../OpenFusion/tdata/patch/1013/drops.json
# path of your xdt JSON file (xdt.json or xdt1013.json)
xdt: ../OpenFusion/tdata/xdt1013.json
# output folder will be created if not present, and the outputs will be inside this folder
output: target/
# yes generates a patch, no generates a single merged drops.json in the "output" folder
generate-patch: yes

# describe how you want to adjust the rarity of items here
items:
  # you can specify items with type name (or type id) and item id pairs...
  - type: Shirt
    id: 245

    # or if the item name uniquely describes the item, you can just use its name and omit type and id
    # though having all 3 specified is totally okay
    name: Open Circuit Shirt

    # then choose one of the below methods to describe the desired rarity of the item
    # we will try to match what is described here
    # if multiple ways are used to describe the rarity of the item, we will use all of them where applicable
    # you will be shown what the achieved real rarity is at the end of the script in the log files

    # approximately how many kills from any mob get you the item, all crate and rarity rolls considered
    kills-till-item: 1200
    # approximately how many kills from certain mobs get you the item, all crate and rarity rolls considered
    # Note that different values will work only if the specified monsters have different drop tables in the game, since we can't just invent new crates to give them
    kills-till-item-per-mob:
      # mob id and the number of kills
      109: 1200
      # or mob name (good idea if it uniquely refers to 1 mob) and the number of kills
      Scoria Cephalopod: 1300
      # mobs not mentioned here will not drop the item if you use the below keyword
      Otherwise: 0

    # approximately how many crates get you the item, all crate and rarity rolls considered
    crates-till-item: 250
    # approximately how many crates from certain mobs get you the item, all crate and rarity rolls considered
    crates-till-item-per-mob:
      109: 40
      Scoria Cephalopod: 120
      Others: 0
    # approximately how many crates from certain crate types get you the item, all crate and rarity rolls considered
    crates-till-item-per-crate-type:
      # negative values will be ignored
      ETC: -1
      # you can also just not mention certain crate types, they will be ignored as well
      # Standard: 10000
      # from the following, depending on the ability and chance to drop the rarity type of this item, the easiest drop chance will be approximately matched, and the others will be set to appropriate values
      Special: 1000
      Sooper: 500
      Sooper Dooper: 100
      Other: 0
      # you can also use aliases for crate types, i.e. Gumball for ETC, Gray for Standard, Bronze or Orange for Special, Silver for Sooper, and Gold for Sooper Dooper
    # approximately how many crates from certain crate types from certain mobs get you the item, all crate and rarity rolls considered
    crates-till-item-per-mob-and-crate-type:
      Scoria Cephalopod:
        Sooper: 300
        Sooper Dooper: 100
    # approximately how many crates from certain crate types from certain mobs get you the item, all crate and rarity rolls considered
    crates-till-item-per-crate-type-and-mob:
      Sooper Dooper:
        109: 40
        Scoria Cephalopod: 120

    # approximately how many kills in certain events get you the item
    event-kills-till-item:
      Knishmas: 1000
      2: 3000
    # approximately how many crates from certain events get you the item
    event-crates-till-item:
      Knishmas: 333
      2: 999

    # approximately how many crates of certain crate types from certain infected zones get you the item
    race-crates-till-item:
      20:
        Gold: 120
      Green Gullet:
        Gold: 120

    # approximately how many mission crates of certain levels get you the item
    mission-crates-till-item:
      # all mission crates of a certain level are assumed to be identical
      36: 12000

    # approximately how many egger eggs from certain areas get you the item
    egger-eggs-till-item:
      # you can use the egger names here: Future, Suburbs, Wilds, Downtown, Darklands
      Wilds:
        Standard: 124
        Sooper Dooper: 10

    # approximately how many golden egg crates from certain areas get you the item
    golden-eggs-till-item:
      # all egg crates from an area is assumed to have the same drop list, so this should be okay
      Mount Blackhead: 34

    # approximately how many of a certain specific crate get you the item
    named-crates-till-item:
      # you can use crate ids or certain names
      100: 10000
      Spring Chicken CRATE: 80

  # let's add an example for another item in the same drop list
  - name: Couture Rifle
    kills-till-item: 12000
  # let's add an example for another item in a separate drop list
  - name: Hot Pants Ray Gun
    crates-till-item-per-crate-type:
      Silver: 500
      Gold: 100
  # follow a similar example for your items, watch the spaces and make sure your text is aligned
  - type: 0
    id: 3
    kills-till-item: 300
